package mx.ipn.logica.ALexico;

public enum Token {
  ASIGNAR,ASIGNAR_MAS,ASIGNAR_MENOS,ASIGNAR_POR,ASIGNAR_DIV,
  IGUAL,DIFERENTE,MAYOR,MENOR,MENOR_IGUAL,MAYOR_IGUAL,
  SUMA,MUL,RESTA,DIV,MOD,POS_INCREMENTO,POS_DECREMENTO,
  AND,OR,COMILLA,COMA,PARENTESIS_ABIERTO,PARENTESIS_CERRADO,LLAVE_ABIERTA,LLAVE_CERRADA,
  GUION_BAJO,DIPLE_ABIERTO,DIPLE_CERRADO,ARROBA_ABIERTO,ARROBA_CERRADO,SI,CONTRASI,
  CONTRA,PARA,HACER,MIENTRAS,CASO,ES,CUANDO,FIN_,ENOTROCASO,VACIO,REGRESA,IMPRIME,ESCRIBE,
  LEE,FONTANA,VALIDO,FALSO,COLECCION,ID,ENT,NAT,RISTRA,GRAF,ERROR

}

